<!-- This example requires Tailwind CSS v2.0+ -->
<template>
    <div
        class="
            bg-white
            px-4
            py-3
            flex
            items-center
            justify-center
            border-gray-200
            sm:px-6
        "
    >
        <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-center">
            <div>
                <nav
                    class="
                        relative
                        z-0
                        inline-flex
                        rounded-md
                        shadow-sm
                        -space-x-px
                    "
                    aria-label="Pagination"
                >
                    <a
                        href="#"
                        class="
                            relative
                            inline-flex
                            items-center
                            px-2
                            py-2
                            rounded-l-md
                            border border-gray-300
                            bg-white
                            text-sm
                            font-medium
                            text-gray-500
                            hover:bg-gray-50
                        "
                    >
                        <span class="sr-only">Previous</span>
                        <i class="fas fa-angle-left"></i>
                    </a>
                    <!-- Current: "z-10 bg-indigo-50 border-indigo-500 text-indigo-600", Default: "bg-white border-gray-300 text-gray-500 hover:bg-gray-50" -->
                    <a
                        href="#"
                        aria-current="page"
                        class="
                            z-10
                            bg-indigo-50
                            border-indigo-500
                            text-indigo-600
                            relative
                            inline-flex
                            items-center
                            px-4
                            py-2
                            border
                            text-sm
                            font-medium
                        "
                    >
                        1
                    </a>
                    <a
                        href="#"
                        class="
                            bg-white
                            border-gray-300
                            text-gray-500
                            hover:bg-gray-50
                            relative
                            inline-flex
                            items-center
                            px-4
                            py-2
                            border
                            text-sm
                            font-medium
                        "
                    >
                        2
                    </a>
                    <a
                        href="#"
                        class="
                            bg-white
                            border-gray-300
                            text-gray-500
                            hover:bg-gray-50
                            hidden
                            md:inline-flex
                            relative
                            items-center
                            px-4
                            py-2
                            border
                            text-sm
                            font-medium
                        "
                    >
                        3
                    </a>
                    <a
                        href="#"
                        class="
                            relative
                            inline-flex
                            items-center
                            px-2
                            py-2
                            rounded-r-md
                            border border-gray-300
                            bg-white
                            text-sm
                            font-medium
                            text-gray-500
                            hover:bg-gray-50
                        "
                    >
                        <span class="sr-only">Next</span>
                        <i class="fas fa-angle-right"></i>
                    </a>
                </nav>
            </div>
        </div>
    </div>
</template>
